[workspace]

resolver = "2"

members = [
    "hello_world",
    "guessing_game",
    "part3_basic",
    "part4_ownership",
    "part5_struct",
    "part6_enum",
    "part7_manage_project",
    "part8_collections",
    
]

default-members = [
    "part8_collections",
]
