[workspace]

resolver = "2"

members = [
    "hello_world",
    "guessing_game",
    "part3_basic",
    "part4_ownership",
    "part5_struct",
    "part6_enum",
    "part7_manage_project",
    "part8_collections",
    "part9_error_handle",
    "sip_hash",
]

default-members = [
    "sip_hash",
]


[profile.release]
lto = true
panic = "abort"
opt-level = 3
