[workspace]

resolver = "2"

members = [
    "hello_world",
    "guessing_game",
    "part3_basic",
    "part4_ownership",
    "part5_struct",
    "part6_enum"
]

default-members = [
    "part6_enum",
]
