[package]
name = "part7_manage_project"
version = "0.1.0"
edition = "2021"

default-run = "part7_manage_project"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"